services:
  - type: web
    name: mindshift-api
    env: docker
    repo: https://github.com/Doryyan/mindshift-backend
    branch: main
    region: oregon
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: USE_SQLITE
        value: "true"
      - key: SECRET_KEY
        generateValue: true
      - key: AI_API_KEY
        sync: false
      - key: DATABASE_URL
        value: "sqlite+aiosqlite:///./mindshift.db"
      - key: DATABASE_URL_SYNC
        value: "sqlite:///./mindshift.db"
    healthCheckPath: /api/v1/health
